Created HUD/UI
vyachkoslav/2Dungeon pull request #28
Opened 2024-11-23 17:02 UTC by wimpula0

2024-11-24 03:26 UTC, vyachkoslav requested changes
Move HUD to the player's scene and split animations logic with damage logic to separate scripts.

2024-11-24 03:26 UTC, vyachkoslav commented on scenes/levels/level 1.tscn
> +[node name="HUD" type="CanvasLayer" parent="."]
Better move the HUD into the player's scene, so there's no need to add separate HUD to each level. Also use the HUD.tscn for that.

2024-11-24 03:26 UTC, vyachkoslav commented on scripts/PlayerAnimations.gd
PlayerAnimations script is meant for animations by definition and we also need interface for damage receiving, so you should either move the animations script to a separate node (like PlayerMovement script) or redefine the purpose of this script.

2024-11-25 17:02 UTC, wimpula0 commented
Couldn't add HUD.tscn to players scene though because of issues with the Hearts Array.

2024-11-25 22:53 UTC, merged